version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum "package.json" }}
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-{{ checksum "package.json" }}
      - run: npm run build
      - store_artifacts:
          path: build
          destination: preview
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - run: ./update.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: source
